POST https://aifactura-czeue2a4bacchxhs.germanywestcentral-01.azurewebsites.net/signup 
Content-Type: application/json

{ "username": "adam", "password": "Pass1234!", "email": "adam23@mail.com" }

###

POST https://aifactura-czeue2a4bacchxhs.germanywestcentral-01.azurewebsites.net/login 
Content-Type: application/json

{ "username": "adam", "password": "Pass1234!" }

###

GET http://127.0.0.1:8000/test_token 
Content-Type: application/json
Authorization: token d28629334cbdec5f42fce2d5a739578bbcf3a3e4
