POST https://aifactura-czeue2a4bacchxhs.germanywestcentral-01.azurewebsites.net/signup 
Content-Type: application/json

{ "username": "adam", "password": "Pass1234!", "email": "adam23@mail.com" }

###

POST https://aifactura-czeue2a4bacchxhs.germanywestcentral-01.azurewebsites.net/login 
Content-Type: application/json

{ "username": "adam", "password": "Pass1234!" }

###

GET http://127.0.0.1:8000/test_token 
Content-Type: application/json
Authorization: token 2213bc86ee354543271336be3d52e7c7b83c15d6
