# Generated by Django 5.0.7 on 2024-08-05 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_registration_number', models.CharField(max_length=50)),
                ('company_tin', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=255)),
                ('company_address_country_subentity', models.CharField(max_length=100)),
                ('company_address_country', models.CharField(default='Romania', max_length=100)),
                ('company_address_country_code', models.CharField(default='RO', max_length=10)),
                ('company_address_country_subentity_code', models.CharField(max_length=10)),
                ('company_address_city', models.CharField(max_length=100)),
                ('company_address_street', models.CharField(max_length=255)),
                ('company_address_details', models.CharField(blank=True, max_length=255, null=True)),
                ('company_vat_status', models.BooleanField(default=False)),
                ('company_vat_number', models.CharField(blank=True, max_length=50, null=True)),
                ('additional_info', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
